package com.example.licenseebe.helper;

public enum Conflict {
    USER_NOT_FOUND,
    GOOGLE_LOG_IN_FAILED,
    CODE_NOT_FOUND,
    EMAIL_NOT_VALID, INCORRECT_PASSWORD, USER_ALREADY_EXISTS, USER_NOT_VALID, NO_BOOKS_IN_DB, BOOK_NOT_FOUND, NO_AUDIO_BOOKS_IN_DB, NO_EBOOKS_BOOKS_IN_DB, IMAGE_SIZE_IS_TOO_BIG, NO_BOOK_CATEGORIES_IN_DB, NO_EVENTS_FOUND, NO_EVENT_FOUND, NO_BOOKS_IN_LIBRARY, NO_USER_FOUND, NO_BOOK_FOUND, NO_BOOKS_IN_CART, NO_BOOKS_IN_WISHLIST, REFRESH_TOKEN_INVALID, ACCESS_TOKEN_IS_EXPIERED, ACCESS_TOKEN_HAS_EXPIERED, ACCESS_TOKEN_INVALID, REVIEW_NOT_FOUND, USERNAME_ALREADY_EXISTS, INVALID_SESSION, INVALID_TOKEN, USER_NOT_ADMIN, INVALID_CODE
}
