package com.example.licenseebe.helper;

public enum Response {
    BOOK_CREATED_SUCCESSFULLY, USER_REGISTERED_SUCCESSFULLY, BOOK_DELETED_SUCCESSFULLY, BOOK_EDITED_SUCCESSFULLY, SUCCESS, UNKNOWN_ERROR, NO_USER_FOUND, NO_BOOK_FOUND, LOG_IN_SUCCESSFUL, RESET_PASSWORD_EMAIL_SENT_SUCCESSFULLY, PASSWORD_CHANGED_SUCCESSFULLY, BOOK_CATEGORY_CREATED_SUCCESSFULLY
}
